import {CUSTOM_ICONS_TYPE} from "@core/typings/icons";

export const SVG_ICONS = {
  lock: 'survey_lock',
  user: 'survey_user',
  certificate: 'survey_certificate',
  document: 'survey_document',
  info: 'survey_info',
  news: 'survey_news',
  notification: 'survey_notification',
  profile: 'survey_profile',
  search: 'survey_search',
  arrow_left: 'survey_arrow_left',
  ped_menu: 'survey_menu',
  arrow_right: 'survey_arrow_right',
  download: 'survey_download',
  calendar: 'survey_calendar',
  gender: 'survey_gender',
  degree: 'survey_degree',
  passport: 'survey_passport',
  scan: 'survey_scan',
  screen: 'survey_screen',
  star: 'survey_star',
  email: 'survey_email',
  location: 'survey_location',
  flag: 'survey_flag',
  low: 'survey_low',
  calendar_check: 'survey_calendar_check',
  calendar_minus: 'survey_calendar_minus',
  phone: 'survey_phone',
  course: 'survey_course',
  doubleCheck: 'survey_double_check',
  calendarPlus: 'survey_calendar_plus',
  bag: 'survey_bag',
  burger: 'survey_burger',
  pointer: 'survey_pointer',
  lang_uz: 'survey_uz',
  lang_ru: 'survey_ru',
  lang_en: 'survey_en',
  lang_qa: 'survey_qa',
  logo: 'survey_logo',
  logo_auth: 'survey_logo_auth',
  survey_telegram: 'survey_telegram',
};




